source:
  type: single_file
  encoding: latin1

mapping:
  customer_id: CustomerID
  transaction_id: InvoiceNo
  transaction_date: InvoiceDate
  product_id: StockCode
  product_name: Description

amount:
  quantity_column: Quantity
  unit_price_column: UnitPrice